services:
  tg-group-bot:
    build: .
    container_name: tg-group-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data:ro
    networks:
      - default
      - panel-net

networks:
  panel-net:
    external: true
    name: 1panel-network
